name: yourly
description: Yet another news reader

version: 1.0.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^0.5.3
  http: ^0.12.0
  equatable: ^0.1.6
  url_launcher: ^5.0.0
  font_awesome_flutter: ^8.2.0
  flutter_webview_plugin: ^0.3.0+2
  fluttertoast: ^2.2.11
  sqflite: ^1.0.0
  rounded_modal: ^1.0.0
  share: ^0.6.0
  package_info: ^0.4.0
  # sticky_headers: ^0.1.7
  timeago: ^2.0.10
  fancy_on_boarding: ^1.1.0
  shared_preferences: ^0.5.0
  webfeed: ^0.4.2
  auto_size_text: ^0.3.0
  intl: ^0.15.7

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/web_hi_res_512.png
    - assets/config.json
    - assets/empty.png
    - assets/onboarding01.png
    - assets/onboarding02.png
    - assets/onboarding03.png
